name: Deploy DotNet project to function app with a Linux environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure_function_app' # set this to the path to your web app project, defaults to the repository root
      AZURE_FUNCTIONAPP_NAME: iot-workload # set this to your application's name
      DOTNET_VERSION: '3.1'

jobs:
  build-and-deploy-function-app:
    runs-on: ubuntu-latest
    steps:

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.3.2
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      
